USE [master]
GO

/****** Object:  Database [BTVN 04]    Script Date: 15/04/2025 10:47:23 ******/
CREATE DATABASE [BTVN 04]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BTVN 04', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.LUONGHOANGVIET\MSSQL\DATA\BTVN 04.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BTVN 04_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.LUONGHOANGVIET\MSSQL\DATA\BTVN 04_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BTVN 04].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BTVN 04] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BTVN 04] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BTVN 04] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BTVN 04] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BTVN 04] SET ARITHABORT OFF 
GO

ALTER DATABASE [BTVN 04] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BTVN 04] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BTVN 04] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BTVN 04] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BTVN 04] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BTVN 04] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BTVN 04] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BTVN 04] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BTVN 04] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BTVN 04] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BTVN 04] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BTVN 04] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BTVN 04] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BTVN 04] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BTVN 04] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BTVN 04] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BTVN 04] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BTVN 04] SET RECOVERY FULL 
GO

ALTER DATABASE [BTVN 04] SET  MULTI_USER 
GO

ALTER DATABASE [BTVN 04] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BTVN 04] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BTVN 04] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BTVN 04] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BTVN 04] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BTVN 04] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BTVN 04] SET QUERY_STORE = ON
GO

ALTER DATABASE [BTVN 04] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [BTVN 04] SET  READ_WRITE 
GO

-- Truy xuat--
SELECT 
    gv.TenGV AS HoTenGV,
    mh.TenMon AS MonDay,
    tkb.GioVao,
    tkb.GioRa
FROM TKB tkb
JOIN GiaoVien gv ON tkb.ID_GV = gv.ID_GV
JOIN MonHoc mh ON tkb.MaMon = mh.MaMon;

-- kiem tra datetime xem co giang vien nao day hoc ko --

SELECT DISTINCT gv.TenGV AS HoTenGV
FROM TKB tkb
JOIN GiaoVien gv ON tkb.ID_GV = gv.ID_GV
WHERE tkb.GioVao < '2025-04-15 11:00:00' 
AND tkb.GioRa > '2025-04-15 09:00:00';

